### ISSUE TITLE
Add docker setup

### ISSUE THREAD

**Issue by JannikStreek** [ether/etherpad-next#66]
Currently there is no docker setup. This is important to make it easier for new developers and deployments later.

Main points:

- [x] Docker setup
- [x] Docker compose setup
- [x] Database setup in compose setup: Postgres vs. mysql

**Comment by AugustinMauroy** [comment]
Also docker should have a mysql instance.
Other point docker can be a dev env.

**Comment by AugustinMauroy** [comment]
@JannikStreek do you want to work on this issue ?

**Comment by JannikStreek** [comment]
> @JannikStreek do you want to work on this issue ?

yes, already on it :) I would suggest Postgres though - or is there a specific reason why you want to use mysql?

**Comment by AugustinMauroy** [comment]
>  I would suggest Postgres though - or is there a specific reason why you want to use mysql?

We can still change. We use Prisma so it's not too complicated but what we're waiting for is to be able to have different providers on a single Prisma client to support different db.
